#!/bin/bash
#SBATCH --job-name=sim4          # Job name
#SBATCH --mail-type=END,FAIL                      # Request status by email 
#SBATCH --mail-user=pb482@cornell.edu        # Email address to send results to.
#SBATCH --nodes=1                                 
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=24:00:00
#SBATCH --partition=default_partition        # Request partition
#SBATCH --gres=gpu:1                  # Type/number of GPUs needed
#SBATCH --exclude=jjs533-compute-03,lil-compute-05,bhattacharjee-compute-02 

trial=$1
algo=$2
num_iter=$3
param1=$4
n_init_evals=$5
noisy_ground_truth_peak=$6

echo "Running trial $trial with algo $algo, num_iter $num_iter, n_init_evals $n_init_evals, noisy_ground_truth_peak $noisy_ground_truth_peak"
echo "param_truth: ($param1)"

/home/pb482/miniconda3/envs/bott/bin/python /home/pb482/bott/runner_file/simulated_runner.py \
    --trial $trial \
    --algo $algo \
    --num_iter $num_iter \
    --param_truth $param1 \
    --n_init_evals $n_init_evals \
    --noisy_ground_truth_peak $noisy_ground_truth_peak
