#!/bin/bash
#SBATCH --job-name=sim4          # Job name
#SBATCH --mail-type=END,FAIL                      # Request status by email 
#SBATCH --mail-user=pb482@cornell.edu        # Email address to send results to.
#SBATCH --nodes=1                                 
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=04:00:00
#SBATCH --partition=frazier        # Request partition
#SBATCH --gres=gpu:nvidia_geforce_rtx_3090:1
#SBATCH --exclude=jjs533-compute-03,lil-compute-05,bhattacharjee-compute-02,unicorn-compute-05,desa-compute-01,unicorn-compute-04,seo-compute-02,shmatikov-compute-01,taylor-compute-01,dgx2-compute-03,sablab-gpu-09,goodfellow,harpo,dgx2-compute-04,rush-compute-01,owens-compute-01,badfellow,eas-shared-compute-01,genai-large-01,abdelfattah-compute-03    

trial=$1
algo=$2
num_iter=$3
param1=$4
n_init_evals=$5
noisy_ground_truth_peak=$6

echo "Running trial $trial with algo $algo, num_iter $num_iter, n_init_evals $n_init_evals, noisy_ground_truth_peak $noisy_ground_truth_peak"
echo "param_truth: ($param1)"
echo "Running on node: $(hostname)"

/home/pb482/miniconda3/envs/bott/bin/python /home/pb482/bott/runner_file/simulated_runner.py \
    --trial $trial \
    --algo $algo \
    --num_iter $num_iter \
    --param_truth $param1 \
    --n_init_evals $n_init_evals \
    --noisy_ground_truth_peak $noisy_ground_truth_peak
