#!/bin/bash
#SBATCH --job-name=sim4          # Job name
#SBATCH --mail-type=END,FAIL                      # Request status by email 
#SBATCH --mail-user=pb482@cornell.edu        # Email address to send results to.
#SBATCH --nodes=1                                 
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=24:00:00
#SBATCH --partition=default_partition        # Request partition
#SBATCH --gres=gpu:1                  # Type/number of GPUs needed
#SBATCH --exclude=jjs533-compute-03,lil-compute-05,bhattacharjee-compute-02 

# Parse arguments
param1='/home/pb482/bott/data/STO38nm_1.5_-1.5mrad_mag.tiff'

# Parse arguments
trial=$1
algo=$2
num_iter=$3
n_init_evals=$4

echo "Running trial $trial with algo $algo, num_iter $num_iter"
echo "param_truth: ($param1)"

/home/pb482/miniconda3/envs/bott/bin/python ./runner_file/STO38_runner.py \
    --trial $trial \
    --algo $algo \
    --num_iter $num_iter \
    --param_truth_path $param1 \
    --n_init_evals $n_init_evals